<x-app-layout>
    <x-slot name="title">Orçamentos</x-slot>
    <x-page-header title="Orçamentos" description="Defina limites por categoria e acompanhe o realizado.">
        <form method="GET" class="flex gap-2"><select name="month" class="form-control !mt-0 !w-auto">@foreach(range(1,12) as $m)<option value="{{ $m }}" @selected($month === $m)>{{ \Carbon\Carbon::create(null,$m)->translatedFormat('F') }}</option>@endforeach</select><select name="year" class="form-control !mt-0 !w-auto">@foreach(range(now()->year-2,now()->year+1) as $y)<option @selected($year===$y)>{{ $y }}</option>@endforeach</select><x-button type="submit" variant="secondary">Ver</x-button></form>
    </x-page-header>
    <div class="grid gap-6 xl:grid-cols-[.72fr_1.28fr]">
        <div class="space-y-4"><form method="POST" action="{{ route('budgets.store') }}" class="surface p-5">@csrf<h2 class="font-bold">Novo orçamento</h2><input type="hidden" name="month" value="{{ $month }}"><input type="hidden" name="year" value="{{ $year }}"><div class="mt-5 space-y-4"><x-form.select label="Categoria" name="category_id" required><option value="">Selecione</option>@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</x-form.select><x-form.input label="Limite mensal" name="limit_amount" data-money-input required /><x-form.textarea label="Observações" name="notes" /><x-button type="submit" class="w-full">Criar orçamento</x-button></div></form>
        <form method="POST" action="{{ route('budgets.copy') }}" class="surface p-5">@csrf<input type="hidden" name="month" value="{{ $month }}"><input type="hidden" name="year" value="{{ $year }}"><h3 class="font-semibold">Ganhe tempo</h3><p class="mt-1 text-sm text-slate-500">Copie os limites do mês anterior sem sobrescrever os já criados.</p><x-button type="submit" variant="secondary" class="mt-4 w-full">Copiar mês anterior</x-button></form></div>
        <div class="space-y-4">
        @forelse($budgets as $row)<article class="surface p-5"><div class="flex items-start justify-between"><div><h2 class="font-bold">{{ $row['budget']->category->name }}</h2><p class="text-sm text-slate-500">Limite <x-money :value="$row['budget']->limit_amount" /></p></div><x-badge :tone="$row['metrics']['level']">{{ $row['metrics']['percentage'] }}%</x-badge></div><div class="mt-5"><x-progress :value="$row['metrics']['percentage']" :tone="$row['metrics']['level']" /></div><div class="mt-4 grid grid-cols-2 gap-4 text-sm"><div><p class="text-xs text-slate-500">Utilizado</p><strong><x-money :value="$row['metrics']['used']" /></strong></div><div><p class="text-xs text-slate-500">Restante</p><strong class="{{ bccomp($row['metrics']['remaining'],'0',2)<0?'text-red-700':'' }}"><x-money :value="$row['metrics']['remaining']" /></strong></div></div><div class="mt-4 flex justify-end gap-1 border-t border-slate-100 pt-3"><a href="{{ route('budgets.edit',$row['budget']) }}" class="btn !min-h-9 !px-3 text-primary-600">Editar</a><form method="POST" action="{{ route('budgets.destroy',$row['budget']) }}" data-confirm="Excluir este orçamento?">@csrf @method('DELETE')<button class="btn !min-h-9 !px-3 text-red-600">Excluir</button></form></div></article>@empty<x-empty-state title="Nenhum orçamento no período" message="Crie limites para suas categorias de despesa." />@endforelse
        </div>
    </div>
</x-app-layout>
