<x-app-layout>
    <x-slot name="title">Relatórios</x-slot><x-page-header title="Relatórios" description="Analise períodos, compare categorias e exporte os dados."><button type="button" onclick="window.print()" class="btn-secondary no-print">Imprimir</button><a href="{{ route('reports.export',request()->query()) }}" class="btn-primary no-print">Exportar CSV</a></x-page-header>
    <form method="GET" class="surface mb-6 grid gap-4 p-4 sm:grid-cols-2 lg:grid-cols-5 no-print"><x-form.select label="Relatório" name="type">@foreach($types as $value=>$label)<option value="{{ $value }}" @selected($type===$value)>{{ $label }}</option>@endforeach</x-form.select><x-form.input label="De" name="start_date" type="date" :value="$filters['start_date']??now()->startOfMonth()->format('Y-m-d')" /><x-form.input label="Até" name="end_date" type="date" :value="$filters['end_date']??now()->endOfMonth()->format('Y-m-d')" /><x-form.select label="Conta" name="account_id"><option value="">Todas</option>@foreach($accounts as $account)<option value="{{ $account->id }}" @selected(($filters['account_id']??null)==$account->id)>{{ $account->name }}</option>@endforeach</x-form.select><div class="flex items-end"><x-button type="submit" class="w-full">Gerar relatório</x-button></div></form>
    @if(in_array($type,['cash_flow','accounts','income_categories','expense_categories','net_worth']))
        <div class="grid gap-4 sm:grid-cols-3"><x-financial-card label="Receitas" :value="$summary['income']" tone="positive" /><x-financial-card label="Despesas" :value="$summary['expense']" tone="negative" /><x-financial-card label="Resultado" :value="$summary['result']" :tone="bccomp($summary['result'],'0',2)>=0?'positive':'negative'" /></div>
        @if(in_array($type,['income_categories','expense_categories']))
            @php($groups=$type==='income_categories'?$summary['by_income_category']:$summary['by_expense_category'])
            <div class="mt-6 grid gap-6 lg:grid-cols-2"><div class="surface p-5"><h2 class="font-bold">Distribuição por categoria</h2><div class="h-80"><canvas data-chart='@json($categoryChart)'></canvas></div></div><div class="surface overflow-hidden"><table class="w-full text-left text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-500"><tr><th class="px-5 py-3">Categoria</th><th class="px-5 py-3 text-right">Total</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($groups as $label=>$value)<tr><td class="px-5 py-4 font-medium">{{ $label }}</td><td class="px-5 py-4 text-right font-bold"><x-money :value="$value" /></td></tr>@empty<tr><td colspan="2" class="px-5 py-10 text-center text-slate-500">Sem dados.</td></tr>@endforelse</tbody></table></div></div>
        @else
            <div class="surface mt-6 overflow-hidden"><div class="overflow-x-auto"><table class="w-full min-w-[760px] text-left text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-500"><tr><th class="px-5 py-3">Data</th><th class="px-5 py-3">Descrição</th><th class="px-5 py-3">Categoria</th><th class="px-5 py-3">Conta</th><th class="px-5 py-3 text-right">Valor</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($transactions as $transaction)<tr><td class="px-5 py-4">{{ $transaction->competence_date->format('d/m/Y') }}</td><td class="px-5 py-4 font-medium">{{ $transaction->description }}</td><td class="px-5 py-4">{{ $transaction->category?->name??'—' }}</td><td class="px-5 py-4">{{ $transaction->account?->name ?? $transaction->creditCard?->name ?? 'Sem conta' }}</td><td class="px-5 py-4 text-right font-bold"><x-money :value="$transaction->amount" /></td></tr>@empty<tr><td colspan="5" class="px-5 py-12 text-center text-slate-500">Nenhum dado no período.</td></tr>@endforelse</tbody></table></div></div>
        @endif
    @elseif($type==='debts')
        <div class="surface overflow-hidden"><table class="w-full text-left text-sm"><thead class="bg-slate-50"><tr><th class="px-5 py-3">Dívida</th><th class="px-5 py-3">Credor</th><th class="px-5 py-3 text-right">Total</th><th class="px-5 py-3 text-right">Pago</th><th class="px-5 py-3 text-right">Saldo</th></tr></thead><tbody class="divide-y divide-slate-100">@foreach($debtRows as $row)<tr><td class="px-5 py-4 font-semibold">{{ $row['model']->name }}</td><td class="px-5 py-4">{{ $row['model']->creditor }}</td><td class="px-5 py-4 text-right"><x-money :value="$row['metrics']['total']" /></td><td class="px-5 py-4 text-right"><x-money :value="$row['metrics']['paid']" /></td><td class="px-5 py-4 text-right font-bold"><x-money :value="$row['metrics']['remaining']" /></td></tr>@endforeach</tbody></table></div>
    @elseif($type==='investments')
        <div class="surface overflow-hidden"><table class="w-full text-left text-sm"><thead class="bg-slate-50"><tr><th class="px-5 py-3">Investimento</th><th class="px-5 py-3">Tipo</th><th class="px-5 py-3 text-right">Investido</th><th class="px-5 py-3 text-right">Atual</th><th class="px-5 py-3 text-right">Rentabilidade</th></tr></thead><tbody class="divide-y divide-slate-100">@foreach($investmentRows as $row)<tr><td class="px-5 py-4 font-semibold">{{ $row['model']->name }}</td><td class="px-5 py-4">{{ $row['model']->type->label() }}</td><td class="px-5 py-4 text-right"><x-money :value="$row['model']->invested_amount" /></td><td class="px-5 py-4 text-right"><x-money :value="$row['model']->current_amount" /></td><td class="px-5 py-4 text-right font-bold">{{ $row['metrics']['return_percentage'] }}%</td></tr>@endforeach</tbody></table></div>
    @else
        <div class="surface overflow-hidden"><table class="w-full text-left text-sm"><thead class="bg-slate-50"><tr><th class="px-5 py-3">Período</th><th class="px-5 py-3">Categoria</th><th class="px-5 py-3 text-right">Planejado</th><th class="px-5 py-3 text-right">Realizado</th><th class="px-5 py-3 text-right">Uso</th></tr></thead><tbody class="divide-y divide-slate-100">@foreach($budgetRows as $row)<tr><td class="px-5 py-4">{{ str_pad($row['model']->month,2,'0',STR_PAD_LEFT) }}/{{ $row['model']->year }}</td><td class="px-5 py-4 font-semibold">{{ $row['model']->category->name }}</td><td class="px-5 py-4 text-right"><x-money :value="$row['model']->limit_amount" /></td><td class="px-5 py-4 text-right"><x-money :value="$row['metrics']['used']" /></td><td class="px-5 py-4 text-right font-bold">{{ $row['metrics']['percentage'] }}%</td></tr>@endforeach</tbody></table></div>
    @endif
</x-app-layout>
